# file		makefile
# date		2008/12/16
# author	kkamagui 
# brief		유틸리티를 생성하기 위한 make 파일

all: ImageMaker

ImageMaker:
	@echo 
	@echo ============= Build ImageMaker ===============
	@echo 
	
	make -C 00.ImageMaker

	@echo 
	@echo =============== Build Complete ===============
	@echo 
	
clean:
	make -C 00.ImageMaker clean
